# Generated by Django 2.1.3 on 2018-11-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendido',
            name='responsaveis',
            field=models.ManyToManyField(to='usuario.Responsavel'),
        ),
    ]
