# Generated by Django 2.1.3 on 2018-11-19 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=2, verbose_name='DDD')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('atendido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Atendido')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
    ]
