# Generated by Django 2.1.3 on 2018-12-08 02:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('turmas', models.ManyToManyField(to='turma.Turma')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
